version: 2
jobs:
 build:
  #  machine: true
   docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: docker:latest
   steps:
    - checkout
    - run: 
        name: perform some test
        command: |
          echo "hasnt been implemented yet ..."
    - run:
        name: Build and push Docker image
        command: |
          TAG="${CIRCLE_SHA1}"
          docker build -t sptkl/cook:$TAG .
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          docker push sptkl/cook:$TAG
          docker tag sptkl/cook:$TAG sptkl/cook:latest
          docker push sptkl/cook:latest